version: '3'
services:
  service1:
    build: springapp
    ports:
      - 1234
    networks:
      - noteapp_network
  service2:
    build: springapp
    ports:
      - 1234
    networks:
      - noteapp_network
  service3:
    build: springapp
    ports:
      - 1234
    networks:
      - noteapp_network

  springapp:
    build: Nginx
    links:
      - service1
      - service2
      - service3
    ports:
      - '1234:1234'
    networks:
      - noteapp_network

  reactapp:
    build: reactapp
    ports:
    - '3000:3000'
    depends_on:
      - springapp
    networks:
      - noteapp_network

networks:
  noteapp_network:
    driver: bridge
